
name: Update README with Bento Stats

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Latest Bento Image URL
        id: fetch_bento_url
        run: |
          API_URL=""
          RESPONSE=
          echo "API Response: "  # Log the entire response
          IMAGE_URL=
          echo "Fetched Image URL: "
          echo "::set-output name=image_url::"

      - name: Delete current README.md
        if: env.skip != 'true'
        run: |
          if [ -f README.md ]; then
            rm README.md
            echo "Deleted old README.md"
          fi

      - name: Create new README.md
        if: env.skip != 'true'
        run: |
          IMAGE_URL=  # Read the URL from last_image_url.txt
          echo "# Bento GitHub Stats" > README.md
          echo "![Bento GitHub Stats]()" >> README.md
          echo "Created new README.md with the latest image URL."

      - name: Commit and Push Changes
        if: env.skip != 'true'
        run: |
          git config --global user.email "subha9.5roy350@gmail.com"
          git config --global user.name "subhadeeproy3902"
          git add .
          git commit -m "Update README with latest Bento stats image"
          git push

